/**
 * -------------------------------------------------------------------------
 * File: server.ts
 * Purpose:
 *    This file is the backend runtime entry point for Angular Universal
 *    (SSR – Server-Side Rendering) using Express on Node.js.
 *
 *    It performs the following:
 *      1. Loads the Angular SSR engine (`AngularNodeAppEngine`)
 *      2. Serves static browser assets (pre-rendered JS/CSS/Images)
 *      3. Handles every incoming HTTP request and returns server-rendered HTML
 *      4. Allows custom Express REST APIs if needed
 *      5. Starts an Express server (only when executed directly)
 *
 * In dAndK Architecture:
 *    - Acts as the universal runtime host for SSR.
 *    - Ensures SEO support, first paint optimization, correct pre-rendering,
 *      and SSR-safe interceptor behavior.
 *    - No business logic or service logic should be written here.
 *
 *    This file should ONLY:
 *        - Serve Angular app via SSR
 *        - Provide optional REST endpoints
 *        - Serve static files
 * -------------------------------------------------------------------------
 */

import {
  AngularNodeAppEngine,
  createNodeRequestHandler,
  isMainModule,
  writeResponseToNodeResponse,
} from '@angular/ssr/node';

import express from 'express';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * -------------------------------------------------------------------------
 * Resolve Build Output Paths
 *
 * serverDistFolder:
 *    Location of the server build output generated by Angular SSR build.
 *
 * browserDistFolder:
 *    Contains client-side build output (HTML, JS, CSS, assets).
 *    These files must be served as static assets.
 * -------------------------------------------------------------------------
 */
const serverDistFolder = dirname(fileURLToPath(import.meta.url));
const browserDistFolder = resolve(serverDistFolder, '../browser');

/**
 * -------------------------------------------------------------------------
 * Initialize Express App and Angular SSR Engine
 *
 * express():
 *    Creates an HTTP server with routing capabilities.
 *
 * AngularNodeAppEngine():
 *    The core Angular SSR engine that executes the Angular app on the server
 *    and returns HTML for each incoming request.
 * -------------------------------------------------------------------------
 */
const app = express();
const angularApp = new AngularNodeAppEngine();

/**
 * -------------------------------------------------------------------------
 * Optional: Define Express REST API Endpoints
 *
 * This allows the same Node server to serve backend APIs
 * (for example: /api/users, /api/login, etc.)
 *
 * DO NOT OVERUSE:
 *    In enterprise apps (like dAndK architecture), backend APIs usually live
 *    in a separate microservice or Spring Boot / NestJS server.
 *
 * Example (commented):
 * -------------------------------------------------------------------------
 *
 * app.get('/api/**', (req, res) => {
 *   res.json({ message: "API is working!" });
 * });
 *
 * -------------------------------------------------------------------------
 */

/**
 * -------------------------------------------------------------------------
 * Serve Static Browser Files
 *
 * express.static():
 *    Serves JS, CSS, images, fonts from /browser directory.
 *
 * maxAge: '1y'
 *    Enables long-term caching for production performance.
 *
 * index: false
 *    Prevents direct index.html serving — SSR engine must handle it instead.
 *
 * redirect: false
 *    Keeps URLs unchanged.
 * -------------------------------------------------------------------------
 */
app.use(
  express.static(browserDistFolder, {
    maxAge: '1y',
    index: false,
    redirect: false,
  }),
);

/**
 * -------------------------------------------------------------------------
 * Main SSR Request Handler
 *
 * Matches all remaining routes using wildcard '/**'.
 *
 * angularApp.handle(req):
 *    Executes Angular on the server for every route.
 *
 * writeResponseToNodeResponse():
 *    Converts Angular SSR output into an Express HTTP response.
 *
 * If Angular does not handle the route:
 *    next() falls through (rare case).
 * -------------------------------------------------------------------------
 */
app.use('/**', (req, res, next) => {
  angularApp
    .handle(req)
    .then((response) =>
      response ? writeResponseToNodeResponse(response, res) : next(),
    )
    .catch(next);
});

/**
 * -------------------------------------------------------------------------
 * Start the Express Server (Only when this file is run directly)
 *
 * isMainModule(import.meta.url):
 *    Ensures the server starts ONLY when executed directly using:
 *        node dist/server/server.mjs
 *
 * If imported by another tool (like Firebase Functions),
 * the server does NOT automatically start.
 *
 * PORT:
 *    Defaults to 4000 if environment variable is not provided.
 * -------------------------------------------------------------------------
 */
if (isMainModule(import.meta.url)) {
  const port = process.env['PORT'] || 4000;
  app.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

/**
 * -------------------------------------------------------------------------
 * Export Request Handler
 *
 * createNodeRequestHandler(app):
 *    Used by Angular CLI dev-server (ng serve) and cloud platforms like:
 *      - Firebase Cloud Functions
 *      - AWS Lambda (API Gateway)
 *      - Vercel Edge Functions
 *
 * It allows frameworks to delegate incoming requests to this Express instance.
 * -------------------------------------------------------------------------
 */
export const reqHandler = createNodeRequestHandler(app);
